---
abstract: 'ActiveSupport equivalent to Perl numeric variables'
author:
  - 'HIROSE Masaaki, C<< <hirose31@gmail.com> >>'
build_requires:
  Test::Base: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: autobox-Numeric-Time
no_index:
  directory:
    - inc
    - t
requires:
  autobox: 2.55
version: 0.02
